[project]
name = "api"
version = "0.1.0"
description = "API for the Winspotter project."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi~=0.118.0",
    "mangum~=0.19.0",
    "pydantic-settings~=2.11.0",
]

[dependency-groups]
dev = [
    "uvicorn~=0.37.0",
]
